spring.application.name=chatapp
spring.datasource.url=jdbc:postgresql://localhost:5432/chatapp
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=cane,gatto,pappagallo,criceto,pulcinoecc